# Legend of Elya — Genesis port
# Builds with marsdev (local m68k-elf-gcc + SGDK 1.81), no Docker needed.
#   toolchain: /home/scott/marsdev/mars

export GDK := /home/scott/marsdev/mars/m68k-elf

.PHONY: build run clean router

# The ROM router table is GENERATED from train/experts.py. It has gone
# stale twice by being regenerated by hand, so the build owns it now.
router:
	python3 tools/gen_router.py

build: router
	$(MAKE) -f $(GDK)/makefile.gen

run: build
	flatpak run com.retrodev.blastem $(CURDIR)/out/rom.bin

clean:
	$(MAKE) -f $(GDK)/makefile.gen clean
