#!/usr/bin/env python3
"""
gen_router.py — generate src/elya_router.h from train/experts.py.

Run by `make build` so the ROM's router table can never go stale against
the shard split. It HAS gone stale twice: once silently (a regeneration
step ran inside a command that aborted early), producing a C router that
disagreed with the Python labels on 15 questions while both looked
individually correct. A generated file that is not generated by the build
is a bug waiting to happen.
"""
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "train"))
import experts as X                                    # noqa: E402

HEADER = '''/* SPDX-License-Identifier: Apache-2.0
 * elya_router.h — GENERATED by tools/gen_router.py from train/experts.py.
 * DO NOT EDIT. Regenerated by `make build`.
 *
 * Deterministic keyword router in ROM. The learned linear router over
 * mean-pooled BYTE embeddings holds 100%% at 4 experts but collapses to
 * ~60%% at 8 (averaging dilutes the one distinctive word), and got WORSE
 * (34%%) with max-pooling added: max over byte embeddings is nearly
 * prompt-invariant, because every English question shares the same common
 * letters, so each dimension saturates on spaces and vowels.
 *
 * These are the SAME plain substrings that produce the training labels,
 * so routing agrees with the shard split by construction rather than by
 * coincidence. Runs once per ANSWER, not per token.
 *
 * %d experts, %d keywords.
 */
#ifndef ELYA_ROUTER_H
#define ELYA_ROUTER_H

#define ER_N_EXPERTS %d
'''

def main():
    n_kw = sum(len(k) for _n, k in X.EXPERTS)
    out = [HEADER % (len(X.EXPERTS), n_kw, len(X.EXPERTS))]
    for i, (name, kws) in enumerate(X.EXPERTS):
        for k in kws:
            if not all(c.isalnum() or c in " -_" for c in k):
                raise SystemExit(
                    f"keyword {k!r} in expert {name!r} is not a plain "
                    "substring; the 68000 router has no regex engine")
        out.append(f"\n/* {name} */\nstatic const char *const ER_KW{i}[] = {{")
        out.append("    " + ", ".join(f'"{k}"' for k in kws) + ", 0")
        out.append("};")
    out.append("\nstatic const char *const *const ER_KW[ER_N_EXPERTS] = {")
    out.append("    " + ", ".join(f"ER_KW{i}" for i in range(len(X.EXPERTS))))
    out.append("};\n")
    out.append("static const char *const ER_NAMES[ER_N_EXPERTS] = {")
    out.append("    " + ", ".join(f'"{n}"' for n, _ in X.EXPERTS))
    out.append("};\n\n#endif")

    dst = ROOT / "src" / "elya_router.h"
    text = "\n".join(out) + "\n"
    if dst.exists() and dst.read_text() == text:
        return                                   # no churn on rebuilds
    dst.write_text(text)
    print(f"gen_router: {len(X.EXPERTS)} experts, {n_kw} keywords -> {dst.name}")

if __name__ == "__main__":
    main()
