/* SPDX-License-Identifier: Apache-2.0
 * elya_router.h — GENERATED by tools/gen_router.py from train/experts.py.
 * DO NOT EDIT. Regenerated by `make build`.
 *
 * Deterministic keyword router in ROM. The learned linear router over
 * mean-pooled BYTE embeddings holds 100% at 4 experts but collapses to
 * ~60% at 8 (averaging dilutes the one distinctive word), and got WORSE
 * (34%) with max-pooling added: max over byte embeddings is nearly
 * prompt-invariant, because every English question shares the same common
 * letters, so each dimension saturates on spaces and vowels.
 *
 * These are the SAME plain substrings that produce the training labels,
 * so routing agrees with the shard split by construction rather than by
 * coincidence. Runs once per ANSWER, not per token.
 *
 * 8 experts, 131 keywords.
 */
#ifndef ELYA_ROUTER_H
#define ELYA_ROUTER_H

#define ER_N_EXPERTS 8


/* origin */
static const char *const ER_KW0[] = {
    "how old are you", "are you old", "are you vintage", "remember being born", "older than this", "when were you born", "what year were you born", "when is your birthday", "your origin", "born in 19", 0
};

/* identity */
static const char *const ER_KW1[] = {
    "who are you", "your name", "where are you from", "your purpose", "flameholder", "are you wise", "what do you love", "a secret", "who made you", "are you alive", "do you dream", "your creator", "do you fear", "are you happy", "can you say no", "you love", "victorian study", 0
};

/* zelda */
static const char *const ER_KW2[] = {
    "zelda", "link", "ganon", "navi", "saria", "malon", "impa", "epona", "triforce", "master sword", "hyrule", "kokiri", "death mountain", "lon lon", "goron", "zora", "ocarina", "temple", "medallion", 0
};

/* quest */
static const char *const ER_KW3[] = {
    "dungeon", "proceed", "lurks", "need here", "help me", "encourage", "quest", "danger", "treasure", "monster", "boss", "realm", "where do i", "what should i", "i am lost", "i am afraid", "should i go", "waits at the end", 0
};

/* rustchain */
static const char *const ER_KW4[] = {
    "rustchain", "rtc", "earn", "node", "epoch", "antiquity", "mining", "miner", "token", "wallet", "attest", "reward", "consensus", "cheat the chain", "much rtc", 0
};

/* retro */
static const char *const ER_KW5[] = {
    "amiga", "c64", "commodore", "apple ii", "atari", "the nes", "snes", "ti-99", "trs-80", "zx spectrum", "6502", "spectrum", "2600", "retro machine", "vintage hardware", 0
};

/* hardware */
static const char *const ER_KW6[] = {
    "g4", "g5", "power8", "altivec", "vec_perm", "big-endian", "endian", "vr4300", "rsp", "rdp", "console", "powerpc", "mips", "68000", "genesis", "runs this", "expansion pak", "n64", "render", "z80", "vdp", "much ram", "chip slow", "this console", 0
};

/* meta */
static const char *const ER_KW7[] = {
    "quantization", "q4", "your model", "language runs you", "how big", "parameters", "neural", "transformer", "how do you think", "how fast do you think", "why ternary", "your experts", "ternary", 0
};

static const char *const *const ER_KW[ER_N_EXPERTS] = {
    ER_KW0, ER_KW1, ER_KW2, ER_KW3, ER_KW4, ER_KW5, ER_KW6, ER_KW7
};

static const char *const ER_NAMES[ER_N_EXPERTS] = {
    "origin", "identity", "zelda", "quest", "rustchain", "retro", "hardware", "meta"
};

#endif
